package com.swag.audit.core;

/**
 * 统一审计事件类型。
 */
public enum AuditEventType {
    REQUEST_RECEIVED,
    REQUEST_COMPLETED,
    REQUEST_FAILED,
    AGENT_STARTED,
    AGENT_COMPLETED,
    AGENT_FAILED,
    AGENT_WAITING_CONFIRMATION,
    TOOL_CALL_REQUESTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_SUCCEEDED,
    TOOL_CALL_FAILED,
    CONFIRMATION_REQUESTED,
    CONFIRMATION_APPROVED,
    CONFIRMATION_DENIED,
    CONFIRMATION_EXPIRED,
    CONFIRMATION_CONSUMED
}
